# Dockerfile for dockerize main_981608115.py
# name: maryam tari
# student number: 981608115
# email:maryamtari15@gmail.com

FROM python:3.7-alpine

WORKDIR /app

COPY main_981608115 /app

CMD [ "python", "main_981608115" ]
