# Dockerfile for dockerize main_981608140.py
# name:Zahra Goleij
# student number:981608140
# email:zahragoleij0@gmail.com

FROM python:3.7-alpine

WORKDIR /app

COPY main_981608140.py /app

CMD [ "python", "main_981608140.py" ]
