# Dockerfile for dockerize main_981608130.py
# Name: Maryam Shokri
# ID: 981608130
# Email:maryam12shokri@gmail.com

FROM python:3.7-alpine

WORKDIR /app

COPY main_981608130.py /app

CMD [ "python", "main_981608130.py" ]
