# Dockerfile for dockerize main_981608113.py
# name:fateme pormehdi
# student number:981608113
# email:amirifateme573@gmail.com

FROM python:3.7-alpine

WORKDIR /app

COPY main_981608113.py /app

CMD [ "python", "main_981608113.py" ]
