# Dockerfile for dockerize main_991608106.py
# Name:Parvin Akbari
# Student Number:991608106
# Email:radparinaz903@gmail.com

FROM python:3.7-alpine

WORKDIR /app

COPY main_991608106.py /app

CMD [ "python", "main_991608106.py" ]
